spring.application.name=hospitalManagement
server.port=8080

# ============================
# Database Configuration
# ============================
spring.datasource.url=jdbc:postgresql://localhost:5432/HospitalDB
spring.datasource.username=postgres
spring.datasource.password=root
server.servlet.context-path=/api/v1

# ============================
# JPA / Hibernate
# ============================
# Use 'update' so schema persists & works with data.sql
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=false

# ============================
# SQL Initialization
# ============================
# Ensures Hibernate creates tables first, then data.sql runs
#spring.jpa.defer-datasource-initialization=true

# Run data.sql every time app starts
#spring.sql.init.mode=always

# Location of data.sql
#spring.sql.init.data-locations=classpath:data.sql


#security config
#spring.security.user.name=kanhaiya
#spring.security.user.password=231fa04f40
jwt.secretKey=adskfjnvso235356tv44verge7ew9rew6tw9ww6wwertet7ete8t99e8rrtgrg6rgr7rbb8ryer6ter5re4er6rey7eryry

#spring.security.oauth2.client.registration.google.client-id=aslfidlas
#spring.security.oauth2.client.registration.google.client-id
